const employees = [
  {
    AFP: "HAB",
    Apellidomaterno: "Cerda",
    Apellidopaterno: "Olivares",
    Cargo: "Gerente de Adminitración y Finanzas",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "ectel@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Alerces 2700, Depto.96-B, Ñuñoa",
    EstadoCivil: "C",
    FechadeIngreso: "2002-04-03 0:00:00",
    Fechadenacimiento: "1974-05-09 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00019",
    Nombre: "Olga",
    Previsiónsocial: "FON",
    RUT: "12.598.063-5",
    Segundonombre: "Beatriz",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "M",
    Telcelasignado: "79772385",
    Telcelparticular: "",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Hab",
    Apellidomaterno: "Muñoz",
    Apellidopaterno: "Beiza",
    Cargo: "Dibujante",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "joaquín.beiza@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Psje.El Hualle 2402 Villa La Foresta, P.Alto",
    EstadoCivil: "C",
    FechadeIngreso: "2006-10-10 0:00:00",
    Fechadenacimiento: "1962-04-15 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00027",
    Nombre: "Joaquín",
    Previsiónsocial: "Fon",
    RUT: "09.095.268-4",
    Segundonombre: "Ignacio",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "M",
    Telcelasignado: "",
    Telcelparticular: "83384029",
    Telfijoparticular: "3196911",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "HAB",
    Apellidomaterno: "Contreras",
    Apellidopaterno: "Cárcamo",
    Cargo: "Gerente General",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Cmdte.Bartolomé Sepúlveda 1475,Provid.",
    EstadoCivil: "C",
    FechadeIngreso: "2002-03-01 0:00:00",
    Fechadenacimiento: "1963-09-24 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00035",
    Nombre: "Eladio",
    Previsiónsocial: "BAN",
    RUT: "08.954.607-9",
    Segundonombre: "Alfonso",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "L",
    Telcelasignado: "77670870",
    Telcelparticular: "92317721",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Prov",
    Apellidomaterno: "Alfaro",
    Apellidopaterno: "Huerta",
    Cargo: "Tecnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Carrera 274, Ovalle",
    EstadoCivil: "",
    FechadeIngreso: "2002-08-01 0:00:00",
    Fechadenacimiento: "1960-10-23 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00043",
    Nombre: "Leonardo",
    Previsiónsocial: "Fon",
    RUT: "09.012.379-3",
    Segundonombre: "del Carmen",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "S",
    Telcelasignado: "",
    Telcelparticular: "92183945",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Prov",
    Apellidomaterno: "Pinto",
    Apellidopaterno: "Pinto",
    Cargo: "Administrativo",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "lpinto@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Av. Ferrocarril 7973 Lo Espejo",
    EstadoCivil: "C",
    FechadeIngreso: "2007-02-26 0:00:00",
    Fechadenacimiento: "1975-10-15 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00078",
    Nombre: "Leonora",
    Previsiónsocial: "Fon",
    RUT: "13.086.972-6",
    Segundonombre: "",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "XL polera",
    Tallapolera: "XXL blusa",
    Telcelasignado: "79771759",
    Telcelparticular: "96271689",
    Telfijoparticular: "5644202",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "",
    Apellidomaterno: "Fuentes",
    Apellidopaterno: "Yelich",
    Cargo: "Técnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Alejandro Gidi,Psje Aurora Chile Nº20,Linares",
    EstadoCivil: "C",
    FechadeIngreso: "2010-03-15 0:00:00",
    Fechadenacimiento: "1966-12-04 0:00:00",
    Fechafiniquito: "2011-12-30 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00086",
    Nombre: "Estanislao",
    Previsiónsocial: "Fon",
    RUT: "10.806.942-2",
    Segundonombre: "José",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "",
    Telcelasignado: "75001717",
    Telcelparticular: "98046138",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "",
    Apellidomaterno: "González",
    Apellidopaterno: "Ramírez",
    Cargo: "Asistente Administrativo",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "cramirez@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "",
    EstadoCivil: "S",
    FechadeIngreso: "2013-10-03 0:00:00",
    Fechadenacimiento: "",
    Fechafiniquito: "2013-12-05 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00094",
    Nombre: "Carolina",
    Previsiónsocial: "",
    RUT: "18.077.300-2",
    Segundonombre: "",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "S",
    Telcelasignado: "",
    Telcelparticular: "",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Pvital",
    Apellidomaterno: "Páez",
    Apellidopaterno: "González",
    Cargo: "Tecnico Integrador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "jgonzalez@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Alerces 2700, Depto.96-B, Ñuñoa",
    EstadoCivil: "C",
    FechadeIngreso: "2002-09-09 0:00:00",
    Fechadenacimiento: "1968-04-08 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00108",
    Nombre: "José",
    Previsiónsocial: "Fon",
    RUT: "11.327.522-7",
    Segundonombre: "Manuel",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "L/M",
    Telcelasignado: "98700267",
    Telcelparticular: "84797818",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Smar",
    Apellidomaterno: "Madrid",
    Apellidopaterno: "Parraguéz",
    Cargo: "Chofer",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Catedral 5030, Quinta Normal",
    EstadoCivil: "",
    FechadeIngreso: "2009-03-01 0:00:00",
    Fechadenacimiento: "1963-07-22 0:00:00",
    Fechafiniquito: "2012-08-31 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00116",
    Nombre: "Rafael",
    Previsiónsocial: "Fon",
    RUT: "09.587.029-5",
    Segundonombre: "Patricio",
    Sexo: "M",
    Tallacalzado: "56",
    Tallapantalón: "46",
    Tallapolera: "XXL",
    Telcelasignado: "",
    Telcelparticular: "",
    Telfijoparticular: "7759381",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "HAB",
    Apellidomaterno: "Bravo",
    Apellidopaterno: "Alarcón",
    Cargo: "Técnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "osval2ab@hotmail.com",
    Domicilioparticular: "Av. Roma 7282, Cerro Navia, Santiago",
    EstadoCivil: "C",
    FechadeIngreso: "2005-03-07 0:00:00",
    Fechadenacimiento: "1969-06-05 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00132",
    Nombre: "Osvaldo",
    Previsiónsocial: "FON",
    RUT: "14.249.599-6",
    Segundonombre: "Bernabé",
    Sexo: "M",
    Tallacalzado: "48/50",
    Tallapantalón: "42",
    Tallapolera: "L",
    Telcelasignado: "76486054",
    Telcelparticular: "88050059",
    Telfijoparticular: "6400586",
    Tipocontrato: "Indefinido",
  },
];

export const cargoPersonal = [
	{
		"Legajo" : "EC00086",
		"Nombre" : "Estanislao",
		"Apellidopaterno" : "Yelich",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00116",
		"Nombre" : "Rafael",
		"Apellidopaterno" : "Parraguéz",
		"Nombrecargo" : "Chofer",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00140",
		"Nombre" : "Willer",
		"Apellidopaterno" : "Surco",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00221",
		"Nombre" : "Rene",
		"Apellidopaterno" : "Rocha",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00280",
		"Nombre" : "Beatriz",
		"Apellidopaterno" : "Carrasco",
		"Nombrecargo" : "Administrativo",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "EC00523",
		"Nombre" : "Ernesto",
		"Apellidopaterno" : "Plaza",
		"Nombrecargo" : "Jefe de Instalaciones",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00582",
		"Nombre" : "Rafael ",
		"Apellidopaterno" : "Ortiz",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00655",
		"Nombre" : "Pamela",
		"Apellidopaterno" : "Vadell",
		"Nombrecargo" : "Ingeniero calculista",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC00809",
		"Nombre" : "Jaime ",
		"Apellidopaterno" : "Mella",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01139",
		"Nombre" : "Orlando",
		"Apellidopaterno" : "Olave",
		"Nombrecargo" : "Seguridad",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "EC01414",
		"Nombre" : "Victor",
		"Apellidopaterno" : "Miranda",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01511",
		"Nombre" : "Magdalena",
		"Apellidopaterno" : "Aros",
		"Nombrecargo" : "Contador",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "EC01651",
		"Nombre" : "Jonathan",
		"Apellidopaterno" : "Martínez",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01856",
		"Nombre" : "Francisco",
		"Apellidopaterno" : "Parra",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01880",
		"Nombre" : "Rody",
		"Apellidopaterno" : "Barrios",
		"Nombrecargo" : "Jefe área eléctrica",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01910",
		"Nombre" : "Lorenzo",
		"Apellidopaterno" : "Ojeda",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01929",
		"Nombre" : "Paolo",
		"Apellidopaterno" : "Viacava",
		"Nombrecargo" : "Técnico eléctrico",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01937",
		"Nombre" : "Miguel",
		"Apellidopaterno" : "Vargas",
		"Nombrecargo" : "Dibujante",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01945",
		"Nombre" : "Ernesto",
		"Apellidopaterno" : "Montesino",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC01961",
		"Nombre" : "Marcela",
		"Apellidopaterno" : "Venegas",
		"Nombrecargo" : "Administrativo",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "EC01996",
		"Nombre" : "Alfredo",
		"Apellidopaterno" : "Bravo",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02070",
		"Nombre" : "Patricio",
		"Apellidopaterno" : "Burgos ",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02151",
		"Nombre" : "Nelson",
		"Apellidopaterno" : "González",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02178",
		"Nombre" : "Ramón",
		"Apellidopaterno" : "Olivares",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02186",
		"Nombre" : "Ana",
		"Apellidopaterno" : "Buhadla",
		"Nombrecargo" : "Experto en prevención de riesgos",
		"Area" : "SSO"
	},
	{
		"Legajo" : "EC02216",
		"Nombre" : "Matias",
		"Apellidopaterno" : "Campos",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02224",
		"Nombre" : "Sebastián",
		"Apellidopaterno" : "Campos",
		"Nombrecargo" : "Técnico Integrador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02348",
		"Nombre" : "Roberto",
		"Apellidopaterno" : "Hanley",
		"Nombrecargo" : "Ingeniero eléctrico",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02364",
		"Nombre" : "Carlos",
		"Apellidopaterno" : "Morales",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02372",
		"Nombre" : "Jorge",
		"Apellidopaterno" : "Maturana",
		"Nombrecargo" : "Jefe de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02380",
		"Nombre" : "Juan",
		"Apellidopaterno" : "Necolhueque",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02542",
		"Nombre" : "Marcelo",
		"Apellidopaterno" : "Zenteno",
		"Nombrecargo" : "Técnico eléctrico",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02569",
		"Nombre" : "Felipe",
		"Apellidopaterno" : "Tapia ",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02577",
		"Nombre" : "Victoria",
		"Apellidopaterno" : "Salvo",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02593",
		"Nombre" : "José",
		"Apellidopaterno" : "Catalán",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02623",
		"Nombre" : "Sebastián",
		"Apellidopaterno" : "Fuenzalida",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02666",
		"Nombre" : "Héctor",
		"Apellidopaterno" : "Tobar",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02712",
		"Nombre" : "César",
		"Apellidopaterno" : "Salinas ",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02720",
		"Nombre" : "Edgar",
		"Apellidopaterno" : "Miranda",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02739",
		"Nombre" : "Leonardo",
		"Apellidopaterno" : "Riquelme",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02747",
		"Nombre" : "Critian",
		"Apellidopaterno" : "Oñate",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02763",
		"Nombre" : "Alejandro ",
		"Apellidopaterno" : "Leiva",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02771",
		"Nombre" : "Sergio",
		"Apellidopaterno" : "Leiva",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02828",
		"Nombre" : "Giselle",
		"Apellidopaterno" : "Sanzana",
		"Nombrecargo" : "Ingeniero calculista",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02909",
		"Nombre" : "Gustavo",
		"Apellidopaterno" : "Contreras",
		"Nombrecargo" : "Ingeniero eléctrico",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC02917",
		"Nombre" : "Roxana",
		"Apellidopaterno" : "Espíndola",
		"Nombrecargo" : "Administrativo",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "EC06548",
		"Nombre" : "Cristóbal",
		"Apellidopaterno" : "Alday",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC07854",
		"Nombre" : "Gino",
		"Apellidopaterno" : "Nobili",
		"Nombrecargo" : "Encargado de Bodega",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC12548",
		"Nombre" : "Jorge",
		"Apellidopaterno" : "Soto",
		"Nombrecargo" : "Técnico Instalador",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC85448",
		"Nombre" : "Rene",
		"Apellidopaterno" : "Matamala",
		"Nombrecargo" : "Encargado de Bodega",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC85472",
		"Nombre" : "Yinet",
		"Apellidopaterno" : "Rodríguez",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC9000K",
		"Nombre" : "María",
		"Apellidopaterno" : "Pardilla",
		"Nombrecargo" : "Ingeniero de proyectos",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "EC99031",
		"Nombre" : "Jorge",
		"Apellidopaterno" : "Olid",
		"Nombrecargo" : "Encargado de Bodega",
		"Area" : "Técnica"
	},
	{
		"Legajo" : "SR00019",
		"Nombre" : "Jocelyn",
		"Apellidopaterno" : "Gómez",
		"Nombrecargo" : "Asistente administrativa",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "SR00175",
		"Nombre" : "Giovanna",
		"Apellidopaterno" : "Cancino",
		"Nombrecargo" : "Administrativo aseo",
		"Area" : "Administracion"
	},
	{
		"Legajo" : "SR00302",
		"Nombre" : "María",
		"Apellidopaterno" : "Cruz",
		"Nombrecargo" : "Administrativo",
		"Area" : "Administracion"
	}
]


export default employees;
