const employees = [
  {
    AFP: "HAB",
    Apellidomaterno: "Cerda",
    Apellidopaterno: "Olivares",
    Cargo: "Gerente de Adminitración y Finanzas",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "ectel@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Alerces 2700, Depto.96-B, Ñuñoa",
    EstadoCivil: "C",
    FechadeIngreso: "2002-04-03 0:00:00",
    Fechadenacimiento: "1974-05-09 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00019",
    Nombre: "Olga",
    Previsiónsocial: "FON",
    RUT: "12.598.063-5",
    Segundonombre: "Beatriz",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "M",
    Telcelasignado: "79772385",
    Telcelparticular: "",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Hab",
    Apellidomaterno: "Muñoz",
    Apellidopaterno: "Beiza",
    Cargo: "Dibujante",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "joaquín.beiza@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Psje.El Hualle 2402 Villa La Foresta, P.Alto",
    EstadoCivil: "C",
    FechadeIngreso: "2006-10-10 0:00:00",
    Fechadenacimiento: "1962-04-15 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00027",
    Nombre: "Joaquín",
    Previsiónsocial: "Fon",
    RUT: "09.095.268-4",
    Segundonombre: "Ignacio",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "M",
    Telcelasignado: "",
    Telcelparticular: "83384029",
    Telfijoparticular: "3196911",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "HAB",
    Apellidomaterno: "Contreras",
    Apellidopaterno: "Cárcamo",
    Cargo: "Gerente General",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Cmdte.Bartolomé Sepúlveda 1475,Provid.",
    EstadoCivil: "C",
    FechadeIngreso: "2002-03-01 0:00:00",
    Fechadenacimiento: "1963-09-24 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00035",
    Nombre: "Eladio",
    Previsiónsocial: "BAN",
    RUT: "08.954.607-9",
    Segundonombre: "Alfonso",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "L",
    Telcelasignado: "77670870",
    Telcelparticular: "92317721",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Prov",
    Apellidomaterno: "Alfaro",
    Apellidopaterno: "Huerta",
    Cargo: "Tecnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Carrera 274, Ovalle",
    EstadoCivil: "",
    FechadeIngreso: "2002-08-01 0:00:00",
    Fechadenacimiento: "1960-10-23 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00043",
    Nombre: "Leonardo",
    Previsiónsocial: "Fon",
    RUT: "09.012.379-3",
    Segundonombre: "del Carmen",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "S",
    Telcelasignado: "",
    Telcelparticular: "92183945",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Prov",
    Apellidomaterno: "Pinto",
    Apellidopaterno: "Pinto",
    Cargo: "Administrativo",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "lpinto@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Av. Ferrocarril 7973 Lo Espejo",
    EstadoCivil: "C",
    FechadeIngreso: "2007-02-26 0:00:00",
    Fechadenacimiento: "1975-10-15 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00078",
    Nombre: "Leonora",
    Previsiónsocial: "Fon",
    RUT: "13.086.972-6",
    Segundonombre: "",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "XL polera",
    Tallapolera: "XXL blusa",
    Telcelasignado: "79771759",
    Telcelparticular: "96271689",
    Telfijoparticular: "5644202",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "",
    Apellidomaterno: "Fuentes",
    Apellidopaterno: "Yelich",
    Cargo: "Técnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Alejandro Gidi,Psje Aurora Chile Nº20,Linares",
    EstadoCivil: "C",
    FechadeIngreso: "2010-03-15 0:00:00",
    Fechadenacimiento: "1966-12-04 0:00:00",
    Fechafiniquito: "2011-12-30 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00086",
    Nombre: "Estanislao",
    Previsiónsocial: "Fon",
    RUT: "10.806.942-2",
    Segundonombre: "José",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "",
    Telcelasignado: "75001717",
    Telcelparticular: "98046138",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "",
    Apellidomaterno: "González",
    Apellidopaterno: "Ramírez",
    Cargo: "Asistente Administrativo",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "cramirez@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "",
    EstadoCivil: "S",
    FechadeIngreso: "2013-10-03 0:00:00",
    Fechadenacimiento: "",
    Fechafiniquito: "2013-12-05 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00094",
    Nombre: "Carolina",
    Previsiónsocial: "",
    RUT: "18.077.300-2",
    Segundonombre: "",
    Sexo: "F",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "S",
    Telcelasignado: "",
    Telcelparticular: "",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Pvital",
    Apellidomaterno: "Páez",
    Apellidopaterno: "González",
    Cargo: "Tecnico Integrador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "jgonzalez@ectel.cl",
    Correoelectrónicopart: "",
    Domicilioparticular: "Los Alerces 2700, Depto.96-B, Ñuñoa",
    EstadoCivil: "C",
    FechadeIngreso: "2002-09-09 0:00:00",
    Fechadenacimiento: "1968-04-08 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00108",
    Nombre: "José",
    Previsiónsocial: "Fon",
    RUT: "11.327.522-7",
    Segundonombre: "Manuel",
    Sexo: "M",
    Tallacalzado: "",
    Tallapantalón: "",
    Tallapolera: "L/M",
    Telcelasignado: "98700267",
    Telcelparticular: "84797818",
    Telfijoparticular: "",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "Smar",
    Apellidomaterno: "Madrid",
    Apellidopaterno: "Parraguéz",
    Cargo: "Chofer",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "",
    Domicilioparticular: "Catedral 5030, Quinta Normal",
    EstadoCivil: "",
    FechadeIngreso: "2009-03-01 0:00:00",
    Fechadenacimiento: "1963-07-22 0:00:00",
    Fechafiniquito: "2012-08-31 0:00:00",
    Fotocarnet: "",
    Legajo: "EC00116",
    Nombre: "Rafael",
    Previsiónsocial: "Fon",
    RUT: "09.587.029-5",
    Segundonombre: "Patricio",
    Sexo: "M",
    Tallacalzado: "56",
    Tallapantalón: "46",
    Tallapolera: "XXL",
    Telcelasignado: "",
    Telcelparticular: "",
    Telfijoparticular: "7759381",
    Tipocontrato: "Indefinido",
  },
  {
    AFP: "HAB",
    Apellidomaterno: "Bravo",
    Apellidopaterno: "Alarcón",
    Cargo: "Técnico Instalador",
    Carnetdeidentidad: "",
    Correoelectrónicoasignado: "",
    Correoelectrónicopart: "osval2ab@hotmail.com",
    Domicilioparticular: "Av. Roma 7282, Cerro Navia, Santiago",
    EstadoCivil: "C",
    FechadeIngreso: "2005-03-07 0:00:00",
    Fechadenacimiento: "1969-06-05 0:00:00",
    Fechafiniquito: "",
    Fotocarnet: "",
    Legajo: "EC00132",
    Nombre: "Osvaldo",
    Previsiónsocial: "FON",
    RUT: "14.249.599-6",
    Segundonombre: "Bernabé",
    Sexo: "M",
    Tallacalzado: "48/50",
    Tallapantalón: "42",
    Tallapolera: "L",
    Telcelasignado: "76486054",
    Telcelparticular: "88050059",
    Telfijoparticular: "6400586",
    Tipocontrato: "Indefinido",
  },
];

export default employees;
