export const courses = [
  {
    CódigoSENCE: "",
    Duración: "8",
    IDCurso: "2",
    Nombrecurso: "Uso y manejo de extintores",
    Organizaciónquelodicta: "Mutual",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "3",
    Nombrecurso: "Rescate en altura",
    Organizaciónquelodicta: "TOK",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "4",
    Nombrecurso: "Izaje de carga",
    Organizaciónquelodicta: "",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "16",
    IDCurso: "5",
    Nombrecurso: "Conducción 4x4",
    Organizaciónquelodicta: "Sercade",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "6",
    Nombrecurso: "Cabalgadura",
    Organizaciónquelodicta: "",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "8",
    IDCurso: "7",
    Nombrecurso: "Trabajo en altura y protección de caídas",
    Organizaciónquelodicta: "TOK",
    Precioestimado: "55000",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "4",
    IDCurso: "8",
    Nombrecurso: "Charla SAI Entel",
    Organizaciónquelodicta: "ENTEL",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "9",
    Nombrecurso: "Curso Inducción minera Mantos Blancos",
    Organizaciónquelodicta: "Mantos Blancos",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "10",
    Nombrecurso: "Toma de conocimiento ingreso seguro",
    Organizaciónquelodicta: "Mantos Blancos",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "4",
    IDCurso: "11",
    Nombrecurso: "Conducción a la defensiva",
    Organizaciónquelodicta: "Mutual",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "",
    Duración: "4",
    IDCurso: "12",
    Nombrecurso: "Primeros auxilios",
    Organizaciónquelodicta: "Mutual",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "",
    Duración: "4",
    IDCurso: "13",
    Nombrecurso: "Orientación en prevención de riesgos",
    Organizaciónquelodicta: "Mutual",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "14",
    Nombrecurso: "Conducción en faena",
    Organizaciónquelodicta: "Mantos Blancos",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "15",
    Nombrecurso: "Curso de inducción BHP Billiton",
    Organizaciónquelodicta: "BHP Billiton",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "30",
    IDCurso: "16",
    Nombrecurso: "Office avanzado",
    Organizaciónquelodicta: "Procasse Ltda.",
    Precioestimado: "114000",
  },
  {
    CódigoSENCE: "",
    Duración: "8",
    IDCurso: "17",
    Nombrecurso: "Uso y manejo de extintores",
    Organizaciónquelodicta: "Precorp",
    Precioestimado: "50000",
  },
  {
    CódigoSENCE: "",
    Duración: "",
    IDCurso: "18",
    Nombrecurso: "Conducción 4x4",
    Organizaciónquelodicta: "Ultracción 4x4",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "",
    Duración: "16",
    IDCurso: "19",
    Nombrecurso: "Trabajo en altura y rescate",
    Organizaciónquelodicta: "",
    Precioestimado: "110000",
  },
  {
    CódigoSENCE: "",
    Duración: "4",
    IDCurso: "20",
    Nombrecurso: "Manejo manual de cargas",
    Organizaciónquelodicta: "Mutual",
    Precioestimado: "0",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "22",
    Nombrecurso: "NSN - Antenna line Installation (ANT_LN_INST)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "23",
    Nombrecurso: "NSN - Antenna line C&I (ANT_LN_C&I)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "24",
    Nombrecurso: "NSN - Flexi MR installation (FLX_MR_ED_INS)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "25",
    Nombrecurso: "NSN - Flexi MR C&I (FLX_MR_ED_C&I)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "26",
    Nombrecurso: "NSN - Flexi 3G Installation (FLX_3G_INST)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "27",
    Nombrecurso: "NSN - Flexi 3G C&I (FLX_3G_C&I)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "28",
    Nombrecurso: "NSN - FPRA Power Installation (FPRA_PWR_INST)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "29",
    Nombrecurso: "NSN - FPRA Power C&I (FPRA_PWR_C&I)",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "30",
    Nombrecurso: "NSN - BS241 2G Inst",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "31",
    Nombrecurso: "NSN - BS241 2G C&I",
    Organizaciónquelodicta: "NSN",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "32",
    Nombrecurso: "Capacitación de inducción Hombre nuevo (Antucoya)",
    Organizaciónquelodicta: "Antucoya",
    Precioestimado: "",
  },
  {
    CódigoSENCE: "N/A",
    Duración: "",
    IDCurso: "33",
    Nombrecurso: "Capacitación de reglamento de tránsito (Antucoya)",
    Organizaciónquelodicta: "Antucoya",
    Precioestimado: "",
  },
];

export const coursesUser = [
  {
    NombreEmpleado: "Olga Olivares",
    cursos: [
      {
        nombreCurso: "Uso y manejo de extintores",
        vigente: true,
        vencimientoProximo: false,
      },
      {
        nombreCurso: "Rescate en altura",
        vigente: true,
        vencimientoProximo: true
      },
      {
        nombreCurso: "Curso Inducción minera Mantos Blancos",
        vigente: false,
        vencimientoProximo: false
      }
    ],
  },
];
