export const empresas = [
    {
        "RazónSocial": "Nokia Solutions and Networks Chile Ltda.",
        "Empresa": "NOKIA",
        "RUT": "76.715.400-3",
        "GIRO": "",
        "DIRECCIÓN": "",
        "RepresentanteLegal": "Rubén Morón\nMauricio Ekstein\nHernán Ávalos",
        "Rut": "",
        "Admin.DeContrato": "",
        "Rut1": "",
        "Mailrepresentantelegal": "",
        "TelefonoEmpresa": ""
    },
    {
        "RazónSocial": "Empresa de Servicio, Instalación y Montaje Esimtel S.A",
        "Empresa": "ESIMTEL S.A",
        "RUT": "99.539.250-K",
        "GIRO": "TELECOMUNICACIONES",
        "DIRECCIÓN": "Alonso de Ovalle 1147, Santiago, Chile",
        "RepresentanteLegal": "Miguel Ángel Tapia Carrasco",
        "Rut": "8.522.969-9",
        "Admin.DeContrato": "Marcela Bravo",
        "Rut1": "15.960.944-8",
        "Mailrepresentantelegal": "",
        "TelefonoEmpresa": ""
    },
    {
        "RazónSocial": "Centinela",
        "Empresa": "",
        "RUT": "",
        "GIRO": "",
        "DIRECCIÓN": "",
        "RepresentanteLegal": "",
        "Rut": "",
        "Admin.DeContrato": "Heidi Urrea",
        "Rut1": "15.482.465-0",
        "Mailrepresentantelegal": "",
        "TelefonoEmpresa": ""
    },
    {
        "RazónSocial": "INFRATEL SPA",
        "Empresa": "",
        "RUT": "76.719.002-6",
        "GIRO": "",
        "DIRECCIÓN": "",
        "RepresentanteLegal": "",
        "Rut": "",
        "Admin.DeContrato": "",
        "Rut1": "",
        "Mailrepresentantelegal": "",
        "TelefonoEmpresa": ""
    },
    {
        "RazónSocial": "MER Infraestructura Chile S.A",
        "Empresa": "MER",
        "RUT": "76.478.810-9",
        "GIRO": "",
        "DIRECCIÓN": "",
        "RepresentanteLegal": "",
        "Rut": "",
        "Admin.DeContrato": "Jorge Hernández",
        "Rut1": "",
        "Mailrepresentantelegal": "",
        "TelefonoEmpresa": ""
    },
    {
        "RazónSocial": "Inportaciones y Servicios Advanced Computing Technologies S.A.",
        "Empresa": "ACT",
        "RUT": "96.609.940-2",
        "GIRO": "TELECOMUNICACIONES",
        "DIRECCIÓN": "Coyancura 2270, piso 11, Providencia, Santiago Chile. ",
        "RepresentanteLegal": "Ivan Retamal Muñoz ",
        "Rut": "5.920.843-8",
        "Admin.DeContrato": "Nermo Soto Mendez",
        "Rut1": "",
        "Mailrepresentantelegal": "ivan.retamal@actsa.net",
        "TelefonoEmpresa": 225881716
    },
]